"""Phase 2 (paper strengthening): quantify whether analyzed_ok rows are a
random subsample of the cohort.

The paper currently asserts in prose that they are not. This backs that
claim with numbers: repo_stars (Mann-Whitney U, since it's a skewed
continuous variable), and ecosystem / version_bump_type / merged (chi-square,
categorical).
"""

import json

import pandas as pd
from scipy.stats import chi2_contingency, mannwhitneyu

from pipeline_utils import DATA_DIR, RESULTS_DIR

DATASET_PATH = DATA_DIR / "analysis_dataset_corrected.csv"
OUT_CSV = RESULTS_DIR / "selection_bias_table.csv"
OUT_TEX = RESULTS_DIR.parent / "paper" / "tables" / "selection_bias.tex"


def mann_whitney_row(name, analyzed, unanalyzed):
    a = analyzed.dropna()
    u = unanalyzed.dropna()
    stat, p = mannwhitneyu(a, u, alternative="two-sided")
    return {
        "variable": name,
        "test": "Mann-Whitney U",
        "analyzed_median": float(a.median()),
        "analyzed_iqr_low": float(a.quantile(0.25)),
        "analyzed_iqr_high": float(a.quantile(0.75)),
        "unanalyzed_median": float(u.median()),
        "unanalyzed_iqr_low": float(u.quantile(0.25)),
        "unanalyzed_iqr_high": float(u.quantile(0.75)),
        "statistic": float(stat),
        "p_value": float(p),
    }


def chi_square_row(name, df, col):
    table = pd.crosstab(df[col].fillna("UNKNOWN"), df["analyzed_ok"])
    chi2, p, _, _ = chi2_contingency(table)
    analyzed_props = (table[True] / table[True].sum()).to_dict() if True in table.columns else {}
    unanalyzed_props = (table[False] / table[False].sum()).to_dict() if False in table.columns else {}
    return {
        "variable": name,
        "test": "chi-square",
        "analyzed_proportions": json.dumps({str(k): round(v, 4) for k, v in analyzed_props.items()}),
        "unanalyzed_proportions": json.dumps({str(k): round(v, 4) for k, v in unanalyzed_props.items()}),
        "statistic": float(chi2),
        "p_value": float(p),
    }


def main():
    df = pd.read_csv(DATASET_PATH)
    df["analyzed_ok"] = df["analyzed_ok"].astype(bool)
    df["merged"] = df["merged_at"].notna()

    analyzed = df[df["analyzed_ok"]]
    unanalyzed = df[~df["analyzed_ok"]]
    print(f"[analyze_selection_bias] analyzed_ok=True: {len(analyzed)}, analyzed_ok=False: {len(unanalyzed)}")

    rows = []
    rows.append(mann_whitney_row("repo_stars", analyzed["repo_stars"], unanalyzed["repo_stars"]))
    rows.append(chi_square_row("ecosystem", df, "ecosystem"))
    rows.append(chi_square_row("version_bump_type", df, "version_bump_type"))
    rows.append(chi_square_row("merged", df, "merged"))

    for row in rows:
        sig = "significant" if row["p_value"] < 0.05 else "not significant"
        print(f"  {row['variable']} ({row['test']}): p={row['p_value']:.4g} ({sig})")
        if row["test"] == "Mann-Whitney U":
            print(f"    analyzed median={row['analyzed_median']:.1f} [{row['analyzed_iqr_low']:.1f}-{row['analyzed_iqr_high']:.1f}]"
                  f" vs unanalyzed median={row['unanalyzed_median']:.1f} [{row['unanalyzed_iqr_low']:.1f}-{row['unanalyzed_iqr_high']:.1f}]")
        else:
            print(f"    analyzed proportions: {row['analyzed_proportions']}")
            print(f"    unanalyzed proportions: {row['unanalyzed_proportions']}")

    out_df = pd.DataFrame(rows)
    out_df.to_csv(OUT_CSV, index=False)

    stars_row = rows[0]
    merged_row = rows[3]
    eco_row = rows[1]
    bump_row = rows[2]

    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    tex = f"""% Auto-generated by analyze_selection_bias.py — do not hand-edit.
\\begin{{table}}[t]
\\caption{{Selection bias: analyzed\\_ok vs.\\ not analyzed}}
\\label{{tab:selection-bias}}
\\centering
\\begin{{tabular}}{{lrr}}
\\toprule
Variable & Test statistic & $p$ \\\\
\\midrule
Repo stars (Mann-Whitney $U$) & {stars_row['statistic']:.1f} & {stars_row['p_value']:.3g} \\\\
Ecosystem ($\\chi^2$) & {eco_row['statistic']:.1f} & {eco_row['p_value']:.3g} \\\\
Version bump type ($\\chi^2$) & {bump_row['statistic']:.1f} & {bump_row['p_value']:.3g} \\\\
Merged ($\\chi^2$) & {merged_row['statistic']:.1f} & {merged_row['p_value']:.3g} \\\\
\\bottomrule
\\end{{tabular}}
\\\\[4pt]
\\footnotesize Analyzed rows: repo stars median {stars_row['analyzed_median']:.0f} (IQR {stars_row['analyzed_iqr_low']:.0f}--{stars_row['analyzed_iqr_high']:.0f}) vs.\\ unanalyzed median {stars_row['unanalyzed_median']:.0f} (IQR {stars_row['unanalyzed_iqr_low']:.0f}--{stars_row['unanalyzed_iqr_high']:.0f}).
\\end{{table}}
"""
    OUT_TEX.write_text(tex, encoding="utf-8")
    print(f"[DONE] analyze_selection_bias — {len(df)} records processed, {len(rows)} tests written")


if __name__ == "__main__":
    main()
